### ISSUE TITLE
Error in drawing 3D boxes on the image

### ISSUE THREAD

**Issue by Hif015** [kuixu/kitti_object_vis#15]
Hello there
I have trouble running the code in some cases when it tries to draw 3d boxes on the image.
line 655, in draw_projected_box3d:
qs = qs.astype(np.int32)
AttributeError: 'NoneType' object has no attribute 'astype'

Thank you!

**Comment by Jihun-Kim-kmu** [comment]
I have same error. Did you solve this error?
