### ISSUE TITLE
support for 3d bbox preds in images

### ISSUE THREAD

**Issue by dmatos2012** [kuixu/kitti_object_vis#21]
Hello,
First, thanks for the amazing library. I noticed i can get predictions with LiDAR, but on images I can only get ground truths but no 3D predictions. 

I noticed the function `def show_image_with_boxes_3type(img, objects, calib, objects2d, name, objects_pred):` was commented out, and if i added it as an arg, it would get me the predictions in 2D as well. 

Any particular reason it got commented out? I think by just adding some modifications from the function `show_image_with_boxes` I can get it to work, but was just curious about it.

Thanks.

**Comment by kuixu** [comment]
Thanks for your feedback and appreciation. It's rarely used at the very beginning. While, currently, It's a good idea that adds an arg for the function you mentioned above. I'll be very happy to get your pull request and merge it immediately.
