### ISSUE TITLE
python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis   system crashed

### ISSUE THREAD

**Issue by MichaelSunEngineer** [kuixu/kitti_object_vis#23]
@kuixu Mayavi Scene 1 display lidar image window black screen does not respond, cmd does not report any error? What can i do? Thanks

**Comment by kuixu** [comment]
Could you show some tail lines in cmd? That info may help to find the possible reason.

In my guess, `no responds` may cause by:
-  too many `DontCare` objects which make the `for` in the cycle of `for--continue--for--continue`
-  something wrong with the installation of mayavi.

**Comment by MichaelSunEngineer** [comment]
I know the reson.it is system problem .python3.6+PyQt4.11.4 is ok. Thanks very much!! You can add this in README

**Comment by kuixu** [comment]
Great! Thanks.
