### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by josy43** [kuixu/kitti_object_vis#28]
When I try to run 
python kitti_object.py --pred
I get following error:
Traceback (most recent call last):
  File "kitti_object.py", line 945, in <module>
    assert os.path.exists(args.dir + "/" + args.split + "/pred")
AssertionError

I also mapped to my results:
./map_pred.sh /data

The mapping might be wrong but I don´t know which format the above Code needs as input.

**Comment by aqqwvfbukn** [comment]
I also encountered the same problem as you

**Comment by arxidinakbar** [comment]
@josy43  got same error, did you fine anything out? please update if any progress, thanks.

**Comment by kuixu** [comment]
@arxidinakbar `--pred` means you try to show predictions with ground truth. But the error above shows that the path (`data/object/training/pred`) not found.  Have you put a directory of prediction (named `pred`) into `data/object/training/` folder?

**Comment by arxidinakbar** [comment]
@kuixu Hi, thank you for the early reply. 
I did place my results(7518 txt files) under data/object/training/pred folder, and when I run the command line: _./map_pred.sh data/object/training/prd_, the error occurs:
```
rm: cannot remove 'data/object/training/pred': Is a directory
```
I checked out the map_pred.sh and know its for set-up a symbolic link to the result folder, just don't know if I follow properly.

**Comment by arxidinakbar** [comment]
@kuixu I carelessly miss the key word 'with ground truth' in your reply, is this flags works for detection results on validation set, since there are no GT labels for testing set.
thank,

**Comment by kuixu** [comment]
> @kuixu Hi, thank you for the early reply.
> I did place my results(7518 txt files) under data/object/training/pred folder, and when I run the command line: _./map_pred.sh data/object/training/prd_, the error occurs:
> 
> ```
> rm: cannot remove 'data/object/training/pred': Is a directory
> ```
> 
> I checked out the map_pred.sh and know its for set-up a symbolic link to the result folder, just don't know if I follow properly.

If you have put the results into `data/object/training/pred`,  that means you have successfully configured, no need to run map_pred.sh.

**Comment by kuixu** [comment]
> @kuixu I carelessly miss the key word 'with ground truth' in your reply, is this flags works for detection results on validation set, since there are no GT labels for testing set.
> thank,

Sorry for that misleading words, I re-edit the reply, the `--pred` option does not require GT labels.

**Comment by arxidinakbar** [comment]
@kuixu I see, then I directly type command line: _python kitti_object.py -p_ and it ran without errors. But no window pops out or no result, is it normal?
To clarify: I put the detection results from KITTI testing set(which is 7518 in total), and I put the results under training folder, is it ok?

thanks.

**Comment by kuixu** [comment]
@arxidinakbar  Sorry for the late reply, I checked the code, the right way to visualize the predictions is to run the command line "python kitti_object.py -p --vis". I am so sorry that the Demo in README is misleading you which has wasted too much of your time.

**Comment by arxidinakbar** [comment]
@kuixu Hi, It's ALL RIGHT since I found your work is very useful. And I would like to make some tiny effort to make it more complete. Would pull request some days later.

Best luck,

**Comment by kuixu** [comment]
@arxidinakbar Happy to hear your appreciation, and looking forward to merging your PR. Haha.
