### ISSUE TITLE
suggestion on mayavi installation

### ISSUE THREAD

**Issue by Keenthan** [kuixu/kitti_object_vis#29]
The latest version of vtk 9.0.1 will make it unsuccessful while installing mayavi.
Here is my suggestion:
> pip install vtk==8.1.2
> conda install pyqt -c conda-forge
> pip install mayavi

**Comment by aqqwvfbukn** [comment]
Have you implemented the picture with 0 on the last box? How can you tell me? Thanks

**Comment by yaobaishen** [comment]
mayavi installation takes so much time, it's quite annoying...
if using 'pip install mayavi', it will failed with error.
Finally below commands work for me:
`pip install vtk==8.1.2`
`conda install pyqt -c conda-forge`
`conda install mayavi -c conda-forge`
