### ISSUE TITLE
can't get 3dbox in image

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [kuixu/kitti_object_vis#30]
$ python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes
just get point cloud image. 3dbox 2dbox display just white
How can i 3dbos in image??
![image](https://user-images.githubusercontent.com/65701965/89532076-30f8e500-d82c-11ea-9407-ea86d20fd18e.png)

**Comment by kuixu** [comment]
Hi @Jihun-Kim-kmu 

Do you solve the problem above? 

According to the log in the terminal, it seems that something wrong (maybe the unmatched version of mayavi) with the gtk.  Have you tried to reinstall the mayavi?

**Comment by Jihun-Kim-kmu** [comment]
Can you tell me which gtk version I should use 2.0 or 3.0? I think gtk version occur error

**Comment by Jihun-Kim-kmu** [comment]
I reinstall with $ conda install mayavi -c conda-forge
and mayavi 4.7.1 , vtk 8.2.0 but same error occur
