### ISSUE TITLE
Fontconfig error: failed reading config file

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [kuixu/kitti_object_vis#31]
Type, truncation, occlusion, alpha: Pedestrian, 0, 0, -0.200000
2d bbox (x0,y0,x1,y1): 712.400000, 143.000000, 810.730000, 307.920000
3d bbox h,w,l: 1.890000, 0.480000, 1.200000
3d bbox location, ry: (1.840000, 1.470000, 8.410000), 0.010000
Difficulty of estimation: Easy
Fontconfig error: failed reading config file

(python:8848): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(python:8848): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(python:8848): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(python:8848): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(python:8848): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(python:8848): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(python:8848): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(python:8848): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'

(python:8848): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(python:8848): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(python:8848): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(python:8848): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)

**Comment by ChunmianLin** [comment]
@Jihun-Kim-kmu Hi, have you solve this problem? I also encounter 'GLib' error, and I don't know how to run the code normally.

**Comment by Jihun-Kim-kmu** [comment]
Hi @ChunmianLin 
I solved problem with this code in my case
# dpkg --force-depends --purge fontconfig-config
# aptitude install fontconfig-config
# dpkg-reconfigure fontconfig-config

**Comment by ChunmianLin** [comment]
Thanks. But I wonder the error information occured in my project is not the same totally as that in your code. 
Actually, in my case, there is not '**failed to read config file**' problem, but the '**GLib-CRITICAL....segmentation fault(core dumped)**' error are reported as the same as you present. I am so confused what cause this problem.
Anyway, many thanks for your value help.

**Comment by Jihun-Kim-kmu** [comment]
maybe I encounter same error haha.....    Are you solved this problem?
(python:22692): GLib-GObject-WARNING **: 19:13:46.651: cannot register existing type 'GdkDisplayManager'

(python:22692): GLib-CRITICAL **: 19:13:46.651: g_once_init_leave: assertion 'result != 0' failed

(python:22692): GLib-GObject-CRITICAL **: 19:13:46.651: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(python:22692): GLib-GObject-WARNING **: 19:13:46.651: invalid (NULL) pointer instance

(python:22692): GLib-GObject-CRITICAL **: 19:13:46.652: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(python:22692): GLib-GObject-WARNING **: 19:13:46.652: invalid (NULL) pointer instance

(python:22692): GLib-GObject-CRITICAL **: 19:13:46.652: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(python:22692): GLib-GObject-WARNING **: 19:13:46.656: cannot register existing type 'GdkDisplay'

(python:22692): GLib-CRITICAL **: 19:13:46.656: g_once_init_leave: assertion 'result != 0' failed

(python:22692): GLib-GObject-CRITICAL **: 19:13:46.656: g_type_register_static: assertion 'parent_type > 0' failed

(python:22692): GLib-CRITICAL **: 19:13:46.656: g_once_init_leave: assertion 'result != 0' failed

(python:22692): GLib-GObject-CRITICAL **: 19:13:46.656: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)

**Comment by ChunmianLin** [comment]
Yes, it is. But I still don't solve the bug. I don't know why this problem cause.

**Comment by Jihun-Kim-kmu** [comment]
I solved problem with $ sudo apt install libcanberra-gtk-module libcanberra-gtk3-module

**Comment by ChunmianLin** [comment]
Thanks for your kind suggestion.
But it seems no effect for my code. I installed these two packages, but it still presents the same error.
