### ISSUE TITLE
error occured when run "python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --pc_label"

### ISSUE THREAD

**Issue by qingzi02010** [kuixu/kitti_object_vis#35]
the shape of the velodyne data is n*4, so error occurred when running "scan.reshape((-1, n_vec))". Here n_vec=5,  caused by the ` if args.pc_label:
            n_vec = 5`       
![image](https://user-images.githubusercontent.com/13197612/94416607-a2f90500-01b1-11eb-8ef5-3b8f43350c81.png)

**Comment by kuixu** [comment]
```
$ python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --pc_label
```

`--pc_label`: Show LiDAR with modified LiDAR file with an additional point cloud label/marker as the 5th dimension(5 vectors: x, y, z, intensity, pc_label). (This option is for the very specific case. If you don't have this type of data, don't use this option).
