### ISSUE TITLE
add -p no image

### ISSUE THREAD

**Issue by liulingfeng123** [kuixu/kitti_object_vis#37]
python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes --ind 100 -p  
then no image

**Comment by kuixu** [comment]
Have you solved this problem？

**Comment by liulingfeng123** [comment]
I did not find a solution to this problem, have you solved it now?

**Comment by kuixu** [comment]
Actually,  we don't have this problem. Have you tried with `--ind 1`?

**Comment by ZRJL** [comment]
Thank you for your reply. I already know what the problem is. The kitti result file I generated only has a test set, so many of them are not. When I use them, I just choose not. thank you very much

**Comment by liulingfeng123** [comment]
Thank you for your reply. I already know what the problem is. The kitti result file I generated only has a test set, so many of them are not. When I use them, I just choose not. thank you very much.

**Comment by kuixu** [comment]
Great!
