### ISSUE TITLE
Own testing data --pred

### ISSUE THREAD

**Issue by enting8696** [kuixu/kitti_object_vis#40]
what a great work , Thanks!

I have own test data and created a testing file , there are calib  image_2  pred  and velodyne in the file.

![Screenshot from 2021-03-23 14-45-33](https://user-images.githubusercontent.com/59861551/112104679-76fd9000-8be6-11eb-8988-25c61733e901.png)

![Screenshot from 2021-03-23 14-46-08](https://user-images.githubusercontent.com/59861551/112104746-8a106000-8be6-11eb-80ac-3fb50a02cfb3.png)

And I run `python kitti_object.py --split testing --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes_ `

The terminal  show : QObject::moveToThread: Current thread (0x564e35f500f0) is not the object's thread (0x564e345b11f0).
Cannot move to target thread (0x564e35f500f0)

And the result in the image and Point Cloud didn't show the label and box.

Is't must to have label file(GT)?   or I did something wrog.

Overall , How to visualize  the pred in the testing file ?

Can you give me some advice?  Grateful！

**Comment by kuixu** [comment]
Sorry for the delayed reply.
It seems that the predicted *txt file is on the wrong path. The right one is `data/object/testing/pred/*.txt`. The topology of the folder is:

```
kitti
    object
        testing
            calib
               000000.txt
            image_2
               000000.png
            label_2
               000000.txt
            velodyne
               000000.bin
            pred
               000000.txt
        training
            calib
               000000.txt
            image_2
               000000.png
            label_2
               000000.txt
            velodyne
               000000.bin
            pred
               000000.txt
```

Hope it may help you.

**Comment by enting8696** [comment]
Thanks for your reply
Your help is effective
