### ISSUE TITLE
show lidar points in img (only in label box）

### ISSUE THREAD

**Issue by enting8696** [kuixu/kitti_object_vis#41]
hi , I have check your code 

And I wanna extract the points that is labeled in lidar 3D box

so, I can use   `--show_lidar_on_image`  , then show the image only have 2D points on labeled objects

Can you give me some advice or hint

**Comment by kuixu** [comment]
Do you mean that only extracting the 2D region(2d box) from the RBG image within labeled lidar objects?

**Comment by enting8696** [comment]
Yes .

**Comment by kuixu** [comment]
2d box is what you need.  You could use the  2d box coordinates (`obj`) to extract the RBG region from `img`. 'https://github.com/kuixu/kitti_object_vis/blob/f05f53d5e409c8009bf6bae89431042afa2bd120/kitti_object.py#L185'

**Comment by enting8696** [comment]
If I also want to extract labeled object lidar point?
Thank help

**Comment by kuixu** [comment]
`imgfov_pts_2d[i, 0], imgfov_pts_2d[i, 1]` is the lidar points in 2d.

https://github.com/kuixu/kitti_object_vis/blob/f05f53d5e409c8009bf6bae89431042afa2bd120/kitti_object.py#L691
