### ISSUE TITLE
run "Show LiDAR with label (5 vector)" is have problem

### ISSUE THREAD

**Issue by shengyuwoo** [kuixu/kitti_object_vis#5]
Hi,kuixu:
    I run the command " $ python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --pc_label " , then occur the fault as following:
data/object training
no pred file
data/object/training/velodyne/000000.bin
Traceback (most recent call last):
  File "kitti_object.py", line 734, in <module>
    dataset_viz(args.dir, args)
  File "kitti_object.py", line 605, in dataset_viz
    pc_velo = dataset.get_lidar(data_idx, dtype, n_vec)[:,0:n_vec]
  File "kitti_object.py", line 74, in get_lidar
    return utils.load_velo_scan(lidar_filename, dtype, n_vec)
  File "/home/wushengyu/kitti_object_vis/kitti_util.py", line 389, in load_velo_scan
    scan = scan.reshape((-1, n_vec))
ValueError: cannot reshape array of size 461536 into shape (5)

**Comment by kuixu** [comment]
I see you used the option '--pc_label'. Is your LiDAR data the raw data from KITTI? If yes please remove option '--pc_label'. The raw LiDAR data has only 4 vectors. The option '--pc_label' is for a new type of data with 5 vectors.

**Comment by ChunmianLin** [comment]
@kuixu @shengyuwoo Hi, what does the '5 vectors' mean? I am a newer to this area.
Thanks.

**Comment by kuixu** [comment]
@ChunmianLin '5 vectors' data type is aiming at supporting someone who provided an additional dimension, such as assigning a label to each point. If you do not meet this need, you could ignore this option.

**Comment by ChunmianLin** [comment]
@kuixu So thanks for your response. I have also encountered the problem of '**(python:12106): GLib-GObject-CRITICAL: assertion 'G_TYPE_IS_OBJECT (object_type)' failed...... segmentation fault(core dumped)**', if I add '**--show_lidar_on_image**' or '**--show_image_with_boxes**' or '**--show_lidar_topview_with_boxes**' parameter. Without these, I can run the code to visualize the lidar or image data.
Why this error occur, and how can I do to solve it?
Thanks in advance.
