### ISSUE TITLE
Could you choose any license?

### ISSUE THREAD

**Issue by fukatani** [kuixu/kitti_object_vis#8]
Hi, thank you for share wonderful library!

By the way, how about licensing this repository?

In github, default lisence is too strict and no one can reproduce (including `git clone`) or create derivative works from your work.
(Please https://help.github.com/en/articles/licensing-a-repository)
So github strongly encourage you to include an open source license such as MIT, BSD, or so on.

I think this repository become more useful if it is licensed.

**Comment by kuixu** [comment]
Thank your appreciation!  An MIT license is added. Hope this could be more helpful.

**Comment by fukatani** [comment]
Definitely helpful for us! Many thanks!
